/* ••[1]••••••••••••••••••••••••• resume-form.labels.ts •••••••••••••••••••••••••••••• */

/* eslint-disable sort-keys */

export const RESUME_FORM_LABELS: Record<string, string> = {
  expandAll: 'Expand all',
  collapseAll: 'Collapse all',
  clear: 'Clear',
  loadTestData: 'Load test data',
  save: 'Save',
  load: 'Load',
  reset: 'Reset',
  submit: 'Submit',
  requiredErrorField: 'This field is required',
  patternErrorField: 'Invalid character on this field',
  savedDataUnavailable: 'Saved data unavailable',
  errorWhileLoadingSavedData: 'Error while loading saved data',
  /* ••[3]••••• Dialogs •••••••••• */
  resetTitle: 'Reset the form',
  resetContent: 'Do you want to reset the form?',
  resetExecuted: 'The form has been reset',
  loadTestDataTitle: 'Load test data onto form',
  loadTestDataContent: 'Do you want to load test data onto the form?',
  loadTestDataExecuted: 'The form has been loaded with test data',
  loadFormTitle: 'Load saved data onto form',
  loadFormContent: 'Do you want to load saved data onto the form?',
  loadFormExecuted: 'The form has been loaded with saved data',
  saveFormTitle: 'Save form data locally',
  saveFormContent: 'Do you want to saved data the form data locally',
  saveFormExecuted: 'The form data has been saved locally',
  /* ••[3]••••• Contact •••••••••• */
  contact: 'Contact',
  contactName: 'Name',
  contactTitle: 'Title',
  /* ••[3]••••• Profile •••••••••• */
  profile: 'Profile',
  profileDescription: 'Description',
  /* ••[3]••••• Capabilities •••••••••• */
  addCapability: 'Add capability',
  removeCapability: 'Remove capability',
  capabilities: 'Capabilities',
  capability: 'Capability',
  capabilityDescription: 'Description',
  capabilityTitle: 'Title',
  /* ••[3]••••• Skills •••••••••• */
  addSkill: 'Add skill',
  removeSkill: 'Remove skill',
  skills: 'Skills',
  skill: 'Skill',
  /* ••[3]••••• Educations •••••••••• */
  addEducation: 'Add education',
  removeEducation: 'Remove education',
  educations: 'Educations',
  education: 'Education',
  educationInstitution: 'Institution',
  educationTitle: 'Title',
  /* ••[3]••••• Certifications •••••••••• */
  addCertification: 'Add certification',
  removeCertification: 'Remove certification',
  certifications: 'Certifications',
  certification: 'Certification',
  certificationDate: 'Date of completion',
  certificationDateHint: 'MM/DD/YYYY',
  certificationInstitution: 'Institution',
  certificationTitle: 'Title',
  /* ••[3]••••• Experiences •••••••••• */
  addExperience: 'Add experience',
  removeExperience: 'Remove experience',
  addSkillToExperience: 'Add skill to experience',
  removeSkillFromExperience: 'Remove skill from experience',
  experiences: 'Experiences',
  experience: 'Experience',
  experienceDateHint: 'MM/DD/YYYY',
  experienceCompany: 'Company',
  experienceEndDate: 'End date',
  experienceProject: 'Project',
  experienceRoleTitle: 'Role title',
  experienceSkills: 'Skills',
  experienceSkill: 'Skill',
  experienceStartDate: 'Start date',
  experienceTechnicalEnvironment: 'Technical environment',
};
